# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 10:58
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('beer_search_v2', '0001_initial'), ('beer_search_v2', '0002_auto_20160404_1343'), ('beer_search_v2', '0003_auto_20160406_1139'), ('beer_search_v2', '0004_auto_20160407_1559'), ('beer_search_v2', '0005_auto_20160407_2311'), ('beer_search_v2', '0006_auto_20160414_1733'), ('beer_search_v2', '0007_untappdentity_product_name'), ('beer_search_v2', '0008_auto_20160414_1812'), ('beer_search_v2', '0009_auto_20160414_1813'), ('beer_search_v2', '0010_auto_20160417_1803'), ('beer_search_v2', '0011_brewery_untappd_id'), ('beer_search_v2', '0012_auto_20160420_1551'), ('beer_search_v2', '0013_auto_20160426_1106'), ('beer_search_v2', '0014_auto_20160427_1115'), ('beer_search_v2', '0015_auto_20160428_1417'), ('beer_search_v2', '0016_auto_20160428_1437'), ('beer_search_v2', '0017_producttype_alternate_names'), ('beer_search_v2', '0018_auto_20160507_1849'), ('beer_search_v2', '0019_auto_20160513_1454'), ('beer_search_v2', '0020_product_atvr_stock'), ('beer_search_v2', '0021_auto_20160712_0930'), ('beer_search_v2', '0022_auto_20160712_0932'), ('beer_search_v2', '0023_remove_producttype_alternate_names'), ('beer_search_v2', '0024_remove_product_source'), ('beer_search_v2', '0025_simplifiedstyle_name_in_sentence'), ('beer_search_v2', '0026_producttype_main_image'), ('beer_search_v2', '0027_product_image_url'), ('beer_search_v2', '0028_modifiablesettings'), ('beer_search_v2', '0029_auto_20160721_1947'), ('beer_search_v2', '0030_auto_20160726_0038'), ('beer_search_v2', '0031_producttypelist'), ('beer_search_v2', '0032_producttypelist_description'), ('beer_search_v2', '0033_auto_20161114_2252'), ('beer_search_v2', '0034_auto_20161114_2253'), ('beer_search_v2', '0035_productlist_visible'), ('beer_search_v2', '0036_auto_20161120_1629'), ('beer_search_v2', '0037_auto_20170401_2156'), ('beer_search_v2', '0038_delete_mainqueryresult')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('untappd_id', models.IntegerField(unique=True)),
                ('alias', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'breweries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('first_seen_at', models.DateTimeField(null=True)),
                ('available', models.BooleanField(default=True)),
                ('temporary', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.ContainerType')),
            ],
            options={
                'ordering': ('name', 'container__name'),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abv', models.FloatField()),
                ('untappd_id', models.IntegerField(blank=True, default=None, null=True)),
                ('untappd_rating', models.FloatField(blank=True, default=None, null=True)),
                ('available', models.BooleanField(default=False)),
                ('needs_announcement', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.Country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SimplifiedStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('html_description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UntappdEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.Brewery')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='UntappdStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('simplifies_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.SimplifiedStyle')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='untappdentity',
            name='style',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.UntappdStyle'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.ProductType'),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'container__name', 'volume')},
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='untappd_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='untappd_id',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='untappd_rating',
        ),
        migrations.RemoveField(
            model_name='untappdentity',
            name='product_type',
        ),
        migrations.AddField(
            model_name='producttype',
            name='untappd_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.UntappdEntity'),
        ),
        migrations.AddField(
            model_name='untappdentity',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='untappdentity',
            name='untappd_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AlcoholCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producttype',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='alcohol_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.AlcoholCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelOptions(
            name='alcoholcategory',
            options={'verbose_name_plural': 'Alcohol categories'},
        ),
        migrations.AlterModelOptions(
            name='untappdentity',
            options={'ordering': ('untappd_id',), 'verbose_name_plural': 'Untappd entities'},
        ),
        migrations.AddField(
            model_name='untappdentity',
            name='product_name',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='atvr_id',
        ),
        migrations.AddField(
            model_name='product',
            name='jog_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='atvr_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='atvr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='untappd_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.Country'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='country_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('alias',)},
        ),
        migrations.CreateModel(
            name='MainQueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_contents', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='producttype',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='mainqueryresult',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='mainqueryresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='available_in_atvr',
        ),
        migrations.AddField(
            model_name='product',
            name='available_in_jog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='atvr_stock',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='simplifiedstyle',
            name='examples',
            field=models.ManyToManyField(blank=True, to='beer_search_v2.ProductType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_in_atvr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simplifiedstyle',
            name='name_in_sentence',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='main_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ModifiableSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'modifiable settings',
            },
        ),
        migrations.CreateModel(
            name='RatebeerEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratebeer_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('number_of_ratings', models.IntegerField()),
                ('levenshtein_confidence', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Ratebeer entities',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='producttype',
            name='ratebeer_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.RatebeerEntity'),
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('products', models.ManyToManyField(to='beer_search_v2.Product')),
                ('description', models.TextField(default='')),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='productlist',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='untappdentity',
            options={'ordering': ('untappd_name',), 'verbose_name_plural': 'Untappd entities'},
        ),
        migrations.RemoveField(
            model_name='untappdentity',
            name='product_name',
        ),
        migrations.AddField(
            model_name='untappdentity',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='untappdentity',
            name='untappd_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='MainQueryResult',
        ),
    ]
