# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0003_auto_20171205_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atvrproduct',
            old_name='untappd_entity',
            new_name='untappd_info',
        ),
    ]
