# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0004_auto_20171205_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atvrproduct',
            name='available_in_atvr',
        ),
    ]
