# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0005_remove_atvrproduct_available_in_atvr'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoGProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jog_id', models.CharField(max_length=10, unique=True)),
                ('price', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('container', models.CharField(choices=[('DS.', 'Dós'), ('FL.', 'Flaska'), ('KÚT', 'Kútur')], max_length=5)),
                ('first_seen_at', models.DateTimeField(null=True)),
                ('available_in_jog', models.BooleanField(default=False)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('untappd_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.UntappdEntity')),
            ],
            options={
                'ordering': ('name', 'container', 'volume'),
            },
        ),
    ]
