# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0006_jogproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogproduct',
            name='jog_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
