# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0006_jogproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atvrproduct',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.ContainerType'),
        ),
        migrations.AlterField(
            model_name='jogproduct',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.ContainerType'),
        ),
        migrations.AlterField(
            model_name='jogproduct',
            name='jog_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
