# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0013_auto_20160426_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('alias',)},
        ),
    ]
