# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:17
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0014_auto_20160427_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainQueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_contents', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='producttype',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
