# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0015_auto_20160428_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainqueryresult',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='mainqueryresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
