# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0016_auto_20160428_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='alternate_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
