# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0018_auto_20160507_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_in_jog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='alternate_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
