# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 21:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0019_auto_20160513_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='atvr_stock',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
