# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0020_product_atvr_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedstyle',
            name='examples',
            field=models.ManyToManyField(to='beer_search_v2.ProductType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='atvr_stock',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_in_atvr',
            field=models.BooleanField(default=False),
        ),
    ]
