# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0021_auto_20160712_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplifiedstyle',
            name='examples',
            field=models.ManyToManyField(blank=True, to='beer_search_v2.ProductType'),
        ),
    ]
