# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0022_auto_20160712_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='alternate_names',
        ),
    ]
