# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0023_remove_producttype_alternate_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='source',
        ),
    ]
