# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0024_remove_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedstyle',
            name='name_in_sentence',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
