# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0025_simplifiedstyle_name_in_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='main_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
