# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0028_modifiablesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifiableSettings',
            new_name='ModifiableSetting',
        ),
    ]
