# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0029_auto_20160721_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatebeerEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratebeer_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('number_of_ratings', models.IntegerField()),
                ('levenshtein_confidence', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Ratebeer entities',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='producttype',
            name='ratebeer_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_search_v2.RatebeerEntity'),
        ),
    ]
