# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0030_auto_20160726_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('products', models.ManyToManyField(to='beer_search_v2.ProductType')),
            ],
        ),
    ]
