# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0032_producttypelist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypelist',
            name='products',
            field=models.ManyToManyField(to='beer_search_v2.Product'),
        ),
    ]
