# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0034_auto_20161114_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
