# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0035_productlist_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlist',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='productlist',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
