# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-02 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_search_v2', '0037_auto_20170401_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainQueryResult',
        ),
    ]
